version: 2
defaults: &defaults
    docker:
      - image: docker:18.06.0-ce-git
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            apk update
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo curl
            apk upgrade
            pip install --upgrade pip
            sudo pip install awscli --upgrade
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo pip install docker-compose
            sudo chmod +x /usr/local/bin/ecs-cli
            
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.3 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .

run_build: &run_build
          name: Installation of build dependencies.
          command: ./build.sh            

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
      
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - run: *run_build

      - deploy:
          command: |
            ./awsconfiguration.sh DEV
            source awsenvconf 
            ./buildenv.sh -e DEV -b submission-processor-es_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,submission-processor-es_appvar -i submission-processor-es
            
    
  "build-prod":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency  
      - run: *install_deploysuite
      - run: *run_build
      - deploy:
          command: |
            ./awsconfiguration.sh PROD
            source awsenvconf 
            ./buildenv.sh -e PROD -b submission-processor-es_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,submission-processor-es_appvar -i submission-processor-es

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only: develop
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master        
