version: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo curl
            pip install --upgrade pip
            sudo pip install awscli --upgrade
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo pip install docker-compose
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Installation of build dependencies.
          command: ./build.sh DEV
      - deploy:
          command: |
            
            git clone --branch devsts https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            ./awsconfiguration.sh DEV
            source awsenvconf 
            ./buildenv.sh -e DEV -b submission-processor-es_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s submission-processor-es_appvar -i submission-processor-es
            
    
  "build-prod":
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo curl
            pip install --upgrade pip
            sudo pip install awscli --upgrade
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo pip install docker-compose
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Installation of build dependencies.
          command: ./build.sh PROD
      - deploy:
          command: |
            git clone --branch v1.1 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            ./master_deploy.sh -d ECS -e PROD -t $CIRCLE_BUILD_NUM -s submission-processor-es  


workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only: develop
      - "build-prod":
          filters:
            branches:
              only: master        
