version: 2
defaults: &defaults
  docker:
  - image: cimg/python:3.11.0-browsers
install_dependency: &install_dependency
  name: Installation of build and deployment dependencies.
  command: |
    sudo apt update
    sudo apt install jq
    sudo apt install python3-pip
    sudo pip3 install awscli --upgrade
    sudo pip3 install docker-compose
    sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    sudo chmod +x /usr/local/bin/ecs-cli

install_deploysuite: &install_deploysuite
  name: Installation of install_deploysuite.
  command: |
    git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
    cp ./../buildscript/master_deploy.sh .
    cp ./../buildscript/buildenv.sh .
    cp ./../buildscript/awsconfiguration.sh .

restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-{{ checksum "yarn.lock" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-{{ checksum "yarn.lock" }}
  paths:
    - node_modules

run_build: &run_build
  name: Installation of build dependencies.
  command: ./build.sh

jobs:
  # Build & Deploy against development backend
  "build-dev":
    !!merge <<: *defaults

    steps:
    # Initialization.
    - checkout
    - setup_remote_docker
    - run: *install_dependency
    - run: *install_deploysuite
    - restore_cache: *restore_cache_settings_for_build
    - run: *run_build
    - save_cache: *save_cache_settings

    - deploy:
        name: Running MasterScript.
        command: "./awsconfiguration.sh DEV\nsource awsenvconf \n./buildenv.sh -e DEV -b submission-processor-es_deployvar\nsource buildenvvar\n./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,submission-processor-es_appvar -i submission-processor-es\n#magic___^_^___line\n#magic___^_^___line\n"
  "build-prod":
    !!merge <<: *defaults
    steps:
    # Initialization.
    - checkout
    - setup_remote_docker
    - run: *install_dependency
    - run: *install_deploysuite
    - restore_cache: *restore_cache_settings_for_build
    - run: *run_build
    - save_cache: *save_cache_settings
    - deploy:
        name: Running MasterScript.
        command: "./awsconfiguration.sh PROD\nsource awsenvconf \n./buildenv.sh -e PROD -b submission-processor-es_deployvar\nsource buildenvvar\n./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,submission-processor-es_appvar -i submission-processor-es\n"
workflows:
  version: 2
  build:
    jobs:
    # Development builds are executed on "develop" branch only.
    - "build-dev":
        context: org-global
        filters:
          branches:
            only:
            - develop
    - "build-prod":
        context: org-global
        filters:
          branches:
            only: master
